export { default as LinkedIn } from './LinkedIn'
export { default as Instagram } from './Instagram'
export { default as Download } from './Download'
export { default as GitHub } from './GitHub'
export { default as Arrow } from './Arrow'
